library(iNEXT)
library(ggplot2)
library("data.table")
data = fread("inext_out_MAR.txt",sep = '\t', header=TRUE)
otutable=as.data.frame(data)
otu=t(otutable)
sp <- specaccum(otutable, method = 'random')
plot(sp, ci.type = 'poly', col = 'blue', lwd = 2, ci.lty = 0, ci.col = 'lightblue')
boxplot(sp, col = 'yellow', add = TRUE, pch = '+')
otu <- iNEXT(otutable, q=1, datatype="abundance",endpoint=3000000)
pdf(file='inext_out_MAR.pdf',width = 5, height = 5)
ggiNEXT(otu, type=1,facet.="order")+theme_bw()+theme(panel.grid=element_blank())+facet_wrap(~order,scales="free")+xlab("Number of MAGs/genomes")+ylab('Number of RiPP clusters')+geom_hline(aes(yintercept=117),colour='grey',linetype="dashed")
dev.off()
